config/routes.rb
RememberMe::Application.routes.draw do

  scope "(:locale)", :locale => /#{Locales.available.keys.join('|')}/ do

    devise_for :users, :controllers => {:registrations => 'users/registrations' }, :path_names => { :sign_in => "log_in", :sign_out => "log_out", :sign_up => "create_account" } do
      get 'users/registrations/success', :to => 'users/registrations#success'
    end

    resources "verboice_schedules"

    resources :schedules, :path => '/reminders' do
      resources :logs, :only => :index
      resources :subscribers, :only => [:index, :destroy]
    end

    match :receive_at, :controller => "nuntium", :action => :receive_at

    resources :channel, :only => [:create, :destroy]

    get "new_channel/:step", :action => :new, :controller => :channel, :as => "new_channel"

    get  'bulk_uploads', :action => :index,  :controller => :bulk_uploads, :as => "bulk_uploads"
    post 'bulk_uploads', :action => :upload, :controller => :bulk_uploads, :as => "bulk_uploads"

    match 'tour/:page' => 'tour#show', :as => :tour
    match 'tour' => 'tour#index'
    match 'help' => 'help#faq'
    match 'community' => 'community#index'

    get  'createAccount', :to => redirect('/%{locale}/users/create_account'), :defaults => { :locale => 'en' }
    get  'discuss',       :to => redirect(RememberMe::Application.config.user_group_url)
    get  'backlog',       :to => redirect(RememberMe::Application.config.backlog_url)

    match '/locale/update' => 'locale#update',  :as => 'update_locale'
    match '/' => 'home#index',                  :as => 'home'

    match 'get_authentication_token' => 'VerboiceSchedules#get_authentication_token', :via => :get
    match 'get_verboice_projects' => 'VerboiceSchedules#get_verboice_projects', :via => :get
    match 'get_verboice_callflows' => 'VerboiceSchedules#get_verboice_callflows', :via => :get
    match 'get_verboice_channels' => 'VerboiceSchedules#get_verboice_channels', :via => :get

  end

  root :to => 'home#index'

end

app/models/verboice_schedule.rb
# Copyright (C) 2011-2012, InSTEDD
# 
# This file is part of Remindem.
# 
# Remindem is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# Remindem is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with Remindem.  If not, see <http://www.gnu.org/licenses/>.

class VerboiceSchedule < ActiveRecord::Base
  validates_presence_of :email, :token, :project_id, :channel_id, :call_flow_id, :welcome_message, :timescale, :title, :keyword
  validates_presence_of :timescale, :unless => Proc.new {|schedule| schedule.type == "CalendarBasedSchedule"}
  validates_uniqueness_of :keyword
  validates_length_of :keyword, :maximum => 15
  validates_format_of :keyword, :with => /^[^ ]+$/, :message => "must not include spaces"
  validates_length_of :title, :maximum => 60
  has_one :schedule, :dependent => :destroy

end

app/controllers/verboice_schedules_controller.rb
# Copyright (C) 2011-2012, InSTEDD
#
# This file is part of Remindem.
#
# Remindem is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Remindem is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Remindem.  If not, see <http://www.gnu.org/licenses/>.

class VerboiceSchedulesController < AuthenticatedController

  def initialize
    super
    @show_breadcrumb = true
    add_breadcrumb _("Reminders"), :schedules_path
  end

  # GET /schedules/1
  # GET /schedules/1.xml
  def show
    @schedule = VerboiceSchedule.find(params[:id])
    add_breadcrumb @schedule.title, verboice_schedule_path(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @schedule }
    end
  end

  def edit
    @schedule = VerboiceSchedule.find(params[:id])
    @schedule.type = @schedule.schedule.type
    add_breadcrumb @schedule.title, verboice_schedule_path(params[:id])
    add_breadcrumb _("Settings"), edit_schedule_path(params[:id])
  end

  def update
    @schedule = VerboiceSchedule.find(params[:id])
    type = params[:verboice_schedule][:type] || nil
    params[:verboice_schedule][:type] = nil
    respond_to do |format|
      if @schedule.update_attributes(params[:verboice_schedule])
        @reminder = @schedule.schedule
        @reminder.title = @schedule.title
        @reminder.keyword = @schedule.keyword
        @reminder.welcome_message = @schedule.welcome_message
        @reminder.timescale = @schedule.timescale
        @reminder.user = current_user
        @reminder.paused = @schedule.paused
        @reminder.type = type if type
        @reminder.verboice_schedule_id = @schedule.id
        @reminder.save!
        format.html { redirect_to(verboice_schedule_url(@schedule), :notice => _('Schedule was successfully updated.')) }
        format.xml  { head :ok }
      else
        add_breadcrumb @schedule.title, verboice_schedule_path(params[:id])
        add_breadcrumb _("Settings"), edit_verboice_schedule_path(params[:id])

        format.html { render :action => "edit" }
        format.xml  { render :xml => @schedule.errors, :status => :unprocessable_entity }
      end
    end
  end

  # GET /schedules/new
  # GET /schedules/new.xml
  def new
    add_breadcrumb _("New Reminder"), :new_verboice_schedule_path
    @schedule = VerboiceSchedule.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @schedule }
    end
  end

  def create
    @schedule = VerboiceSchedule.new(params[:verboice_schedule])
    # @schedule.type = params[:verboice_schedule][:type]
    respond_to do |format|
      if @schedule.save!
        @reminder = Schedule.new()
        @reminder.title = @schedule.title
        @reminder.keyword = @schedule.keyword
        @reminder.user = current_user
        @reminder.welcome_message = @schedule.welcome_message
        @reminder.timescale = @schedule.timescale
        @reminder.type = params[:verboice_schedule][:type]
        @reminder.verboice_schedule_id = @schedule.id
        @reminder.save!
        format.html { redirect_to(schedules_url(), :notice => _('Verboice Schedule was successfully created.')) }
        format.xml  { render :xml => @schedule, :status => :created, :location => @schedule }
      else
        add_breadcrumb _("New Reminder"), :new_verboice_schedule_path
        format.html { render :action => "new" }
        format.xml  { render :xml => @schedule.errors, :status => :unprocessable_entity }
      end
    end
  end

  def get_authentication_token
    url = VerboiceConfig::Config["url"] + "/api2/auth"
    variable = {'account[email]' => params[:email], 'account[password]' => params[:password]}
    res = request_verboice(url, variable, "post")
    if res.code == "200"
      render :json => res.body
    else
      render :text => "Error", :status => 500
    end
  end

  def get_verboice_projects
    url = VerboiceConfig::Config["url"] + "/api2/projects"
    variable = {'email' => params[:email], 'token' => params[:token]}
    res = request_verboice(url, variable, "get")
    if res.code == "200"
      render :text => res.body
    else
      render :text => "Error", :status => 500
    end
  end

  def get_verboice_callflows
    url = VerboiceConfig::Config["url"] + "/api2/call_flows"
    variable = {'email' => params[:email], 'token' => params[:token]}
    res = request_verboice(url, variable, "get")
    if res.code == "200"
      render :text => res.body
    else
      render :text => "Error", :status => 500
    end
  end

  def get_verboice_channels
    url = VerboiceConfig::Config["url"] + "/api2/channels"
    variable = {'email' => params[:email], 'token' => params[:token]}
    res = request_verboice(url, variable, "get")
    if res.code == "200"
      render :text => res.body
    else
      render :text => "Error", :status => 500
    end
  end

  private

  def request_verboice(url, variable, method)
    case method
    when "post"
      req = Net::HTTP::Post.new(url)
    when "get"
      req = Net::HTTP::Get.new(url)
    end
    uri = URI(url)
    req.set_form_data(variable)
    res = Net::HTTP.start(uri.hostname, uri.port) do |http|
      http.request(req)
    end
  end

end

app/views/verboice_schedules/_form.html.haml
- content_for :head do
  = javascript_include_tag 'schedules'
= form_for @schedule, :validate => true do |f|
  = errors_for @schedule, :as => :reminder
  .field.w60
    = f.label :titleapp, _("Title")
    = f.text_field :title, :class => "causesPendingSaveNoticeOnChange"
  .field.w60
    = f.label :keyword, _("Keyword")
    %p Users will register with this keyword
    = f.text_field :keyword, :class => "causesPendingSaveNoticeOnChange"
  .field
    = f.label :welcome_message, _("Welcome message")
    %p This is the message users will get after they successfully registered
    .w60
      = f.text_area :welcome_message,                          |
        :rows => 3,                                            |
        :class => "causesPendingSaveNoticeOnChange ux-wajbar", |
        :placeholder => _('Write your welcome message here'),  |
        :maxlength => 160    
  .field
    = f.label :timescale, _("Timescale")
    %p Choose timescale reference to use
    .ux-dropdown.w20.inline
      = f.select :timescale, Schedule.time_scale_options, {}, :class => "causesPendingSaveNoticeOnChange"
  .field
    %label Mode
    %p
      = _("Choose whether you want to set up a timeline for your messages or call them randomly")
      = _("(Only available if there are no subscribers)") unless (@schedule.schedule.nil? or @schedule.schedule.subscribers.empty?)
    = f.radio_button :type,                               |
      "FixedSchedule",                                    |
      :id => "fixed_schedule_option",                     |
      :class => "causesPendingSaveNoticeOnChange styled", |
      :disabled => !(@schedule.schedule.nil? or @schedule.schedule.subscribers.empty?)          |

    = f.label :type, FixedSchedule.mode_in_words, :class => 'radio'
    %br/
    = f.radio_button :type,                               |
      "RandomSchedule",                                   |
      :id => "random_schedule_option",                    |
      :class => "causesPendingSaveNoticeOnChange styled", |
      :disabled => !(@schedule.schedule.nil? or @schedule.schedule.subscribers.empty?),         |
      'data-message' => _("Random Once")                  |
    = f.label :type, RandomSchedule.mode_in_words, :class => 'radio'
  %hr/
  %br
  .field
    = f.label :welcome_message, _("Verboice Configuration")
    %p This is the authentication that connect from remindem to verboice
    .w60
      = f.label :email, _("Email"), :class => "required"
      = f.email_field :email
  .field
    .w60
      = f.label "Password", :class => "required"
      %input{:type => 'password', :id => 'password' }
  
  = f.password_field :token, :style => 'display:none;'

  .actions
    %button.white{:type => "button", :onclick => "authenticate_verboice()"} Authenticate
  %br
  .field.w60
    = f.label :project_id, _("Project"), :class => "required"
    = f.select :project_id, options_for_select(["Select verboice project"]), {},{ :onclick => 'changeProject(this)' }
  .field.w60
    = f.label :call_flow_id, _("Call Flow"), :class => "required"
    = f.select :call_flow_id, options_for_select(["Select verboice call flow"])
  .field.w60
    = f.label :channel_id, _("Channel"), :class => "required"
    = f.select :channel_id, options_for_select(["Select verboice channel"])
  = f.text_field "hiddenId", :value => @schedule.id, :style => 'display:none;', :id => 'tmpId', :name => 'tmpId'
  = f.text_field "hiddenProject", :value => @schedule.project_id, :style => 'display:none;', :id => 'tmpProjectId', :name => 'tmpProjectId'
  = f.text_field "hiddenProject", :value => @schedule.call_flow_id, :style => 'display:none;', :id => 'tmpCallFlowId', :name => 'tmpCallFlowId'
  = f.text_field "hiddenChannel", :value => @schedule.channel_id, :style => 'display:none;', :id => 'tmpChannelId', :name => 'tmpChannelId'

  .actions
    %button.white{:type => "submit"} Save

app/views/verboice_schedules/_message_add.html.haml
= render "message_fields", :f => f
= render "message_controls", :f => f, :save_onclick => 'confirm_add(this);', :cancel_onclick => 'revert_add(this);'

app/views/verboice_schedules/_message_controls.html.haml
- save_onclick ||= 'confirm_changes(this);'
- cancel_onclick ||= 'revert_changes(this);'
%li.fields
  .box.w60.reminderMessageBox
    = link_to_remove_fields '', f, :class => "fdelete causesPendingSaveNoticeOnClick"
    .offset.left
      .ux-nstep
        = tag :input, :name => "edit_offset", :size => "2", :type => "text", :value => f.object.offset, :onblur => "validate_onblur(this);", :'data-min' => "0"
      %span.timescale= @schedule.timescale
    .text
      = content_tag :textarea, f.object.text, :rows => 4, :class => "ux-wajbar w60", :placeholder => _('Add message here'), |
        :name => "edit_text" , :maxlength => 160, :onblur => "validate_onblur(this);"                                    |
    %hr/
    .actions
      %button.white{:onclick => "return #{save_onclick}", :type => "button"} Save
      %a{:href => "#", :onclick => "#{cancel_onclick}; return false;"} Cancel

app/views/verboice_schedules/_message_fields.html.haml
%li.fields
  = errors_for f.object, :as => :message
  .box.grey.w60.reminderMessageBox.closed
    = link_to_remove_fields '', f, :class => "fdelete causesPendingSaveNoticeOnClick"
    .left.offset
      = f.hidden_field :offset, :class => "offset"
      After
      %span.offset= f.object.offset
      %span.timescale= @schedule.timescale
    = f.hidden_field :text, :class => "hidden text"
    %pre.aleft.text.w55= f.object.text
    %span.aleft
      = link_to_edit_fields "Edit", f, :messages
    .clear

app/views/verboice_schedules/edit.html.haml
- content_for :head do
  :javascript
    $(function() {
      connectVerboice();
    })
= render "shared/schedule_tabs_and_title", :schedule => @schedule.schedule
.tabsline
  %h2 Properties
  %p Below you can configure this Reminder properties
  = render 'form'

app/views/verboice_schedules/index.html.haml
- content_for :head do
  :javascript
    $(function() {
      $('.ItemsTable tr').live('click', function() {
        var anchor = $('a', $(this));
        if (anchor.length > 0) {
          window.location = anchor.attr('href');
        }
      });

      $(".filterSchedules").change(function () {
        $(".filterSchedules option:selected").each(function () {
          window.location = $(this).val();
        });
      });
    })

%h1 Reminders
.tablewrapp.RemindersTable
  %table{:class => "GralTable TwoColumn CleanTable ItemsTable #{'empty' if @schedules.empty?}"}
    %tr
      %th My Reminders
      %th
        = content_tag :select, :class => 'filterSchedules', :disabled => !@at_least_one_schedule_is_paused do
          = options_for_select([                                                                                  |
              [_('Show All'),'all'],                                                                              |
              [_('Paused'),'paused'],                                                                             |
              [_('Running'),'running']                                                                            |
            ].map { |text,show| [text, schedules_path(:show => show)] }, schedules_path(:show => params[:show]) ) |
    - if @schedules.empty?
      %tr
        %td{:colspan => "2"}
          .EmptyRemindersTable
            - if params[:show] == 'running'
              You have no running Reminders
            - else
              You have no Reminders yet
            %br/
            = link_to _('Create Reminder'), new_schedule_path, :class => 'EmptyAddLink'
            = link_to '', new_schedule_path, :class => 'EmptyAddButton button cadd'
    - else
      - @schedules.each do |schedule|
        %tr
          %td{:class => schedule.paused? ? 'spaused' : 'sactive'}
            %span
            = link_to schedule_path(schedule) do
              = schedule.title
              .indexKeyword
                \&#x2192;
                = schedule.keyword
          %td= link_to '', schedule_path(schedule), :class => 'farrow'
      %tr
        %td
          Create Reminder
        %td
          = link_button_to '', new_schedule_path, :class => 'cadd i18b-groupChat'
          = link_button_to '', new_verboice_schedule_path, :class => 'cadd i18b-phone'

- if current_user.feature_enabled?(:bulk_upload)
  %p= link_to _("Subscribers bulk upload"), bulk_uploads_path, :class => 'farrow'

= render :partial => 'channel/user_channel'

app/views/verboice_schedules/new.html.haml
%h1 New verboice reminder
= render 'form'

app/views/verboice_schedules/show.html.haml
- content_for :head do
  :javascript
    function updateNotifyValue(){
    	if ($('#notifySubscribers:checked').val() !== undefined) {
    		send_notification = true;
    	}else {
    		send_notification = false;
    	}
    	$('#delete').attr('href', ($('#delete').attr('href').replace("NOTIFY_VALUE", send_notification)));
    };
= render "shared/schedule_tabs_and_title", :schedule => @schedule.schedule
.tabsline
  %h2 Status
  %p Here you can see the overall status of your schedule
  = render 'subscribers/download_as_csv', :schedule => @schedule.schedule
  %hr/
  %h2 Properties
  %p This is a summary of the properties of your schedule
  .left.box.plain.white.overviewBox
    .i48grad-key.left
    .overviewText
      Keyword
      %br/
      = @schedule.keyword
  .left.box.plain.white.overviewBox
    .i48grad-time.left
    .overviewText
      = "#{@schedule.schedule.duration} #{@schedule.timescale}"
      %br/
      = @schedule.schedule.class.mode_in_words
  .left.box.plain.white.overviewBox
    .i48grad-reminder.left
    .overviewText
      = @schedule.schedule.messages.count
      calls
      %br>/
      queued
  .clear
  = link_to _('Edit settings'), edit_verboice_schedule_path(@schedule), :class => 'farrow overviewButton'
  = form_for(@schedule) do |f|
    %p.pausedDescription
      - if @schedule.paused?
        = _("This Reminder is paused and won't send messages.")
      - else
        = _("This Reminder is active and will be sending messages to registered users.")
    = f.hidden_field :paused?, :value => !@schedule.paused?
    - if @schedule.paused?
      %button.fplay.overviewButton{:type => "submit"} Start this reminder
    - else
      %button.fpause.overviewButton{:type => "submit"} Pause this reminder
  %hr/
  .ux-collapsible.collapsed.deleteScheduleBox.switch{"data-on-expanded" => "box grey plain expanded"}
    %span
      %a.icon.fdelete.ux-collapse-trigger.black{:href => "#"} Delete this reminder
    .ux-content
      %a.icon.fdelete.ux-collapse-trigger{:href => "#"}
        Are you sure you want to delete this reminder?
        %br/
        All your subscribers will stop receiving the scheduled messages
      %hr/
      %input#notifySubscribers{:checked => "", :name => "notifySubscribers", :type => "checkbox"}/
      = label_tag :notifySubscribers, "Notify the subscribers that this reminder is no longer active?"
      = link_to 'Confirm', schedule_path(@schedule.schedule, :notify => "NOTIFY_VALUE"), :method => :delete , :class => "button white right", :id => "delete", :onclick => "updateNotifyValue();"
      %a.ux-collapse-trigger.grey.right{:href => "#"} Cancel